name: CI

on:
  push:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:
  index:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Download libsolv from github release
      uses: robinraju/release-downloader@v1
      with:
        repository: 'tanhaoqiang/libsolv'
        latest: true
        fileName: '*.whl'
        out-file-path: pypi/solv

    - run: |
        cat > pypi/index.html <<EOF
        <!DOCTYPE html>
        <html><body><a href="solv/">solv</a></body></html>
        EOF

        cat >> pypi/solv/index.html <<EOF
        <!DOCTYPE html>
        <html><body>
        EOF

        for name in $(ls -1 pypi/solv/*.whl | xargs -I {} basename {})
        do
          echo "<a href="${name}#sha256=$(sha256sum pypi/solv/${name} | cut -d " " -f 1)">${name}</a>" >> pypi/solv/index.html
        done

        cat >> pypi/solv/index.html <<EOF
        </body></html>
        EOF

    - uses: actions/upload-artifact@v4
      with:
        name: pypi-solv
        path: ./pypi/

  ci:
    needs:
    - index
    runs-on: 'ubuntu-latest'
    steps:

    - uses: actions/download-artifact@v4
      with:
        name: pypi-solv
        path: pypi

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: pip install -i "file://${{ github.workspace }}/pypi" solv

    - name: Checkout
      uses: actions/checkout@v4

    - run: pip install -e .

    - run: |
        cd examples/hello-lib
        python -mcod

        cd ../hello-bin
        python -mcod
