name: CI

on:
  push:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:
  ci:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        python:
        - "3.12"
        - "3.13"

    runs-on: '${{ matrix.os }}'

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.python }}'

    - run: pip install -i "https://tanhaoqiang.github.io/simple" solv

    - name: Checkout
      uses: actions/checkout@v4

    - run: pip install -e .

    - run: python -munittest tests
