name: CI

on:
  push:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:
  index:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Download libsolv from github release
      uses: robinraju/release-downloader@v1
      with:
        repository: 'tanhaoqiang/libsolv'
        latest: true
        fileName: '*.whl'
        out-file-path: pypi/solv

    - run: |
        cat > pypi/index.html <<EOF
        <!DOCTYPE html>
        <html><body><a href="solv/">solv</a></body></html>
        EOF

        cat >> pypi/solv/index.html <<EOF
        <!DOCTYPE html>
        <html><body>
        EOF

        for name in $(ls -1 pypi/solv/*.whl | xargs -I {} basename {})
        do
          echo "<a href="${name}#sha256=$(sha256sum pypi/solv/${name} | cut -d " " -f 1)">${name}</a>" >> pypi/solv/index.html
        done

        cat >> pypi/solv/index.html <<EOF
        </body></html>
        EOF

    - uses: actions/upload-artifact@v4
      with:
        name: pypi-solv
        path: ./pypi/

  ci:
    needs:
    - index
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        python:
        - "3.12"
        - "3.13"

    runs-on: '${{ matrix.os }}'

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: pypi-solv
        path: pypi

    - uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.python }}'

    - run: pip install -i "${{ github.workspace }}/pypi" solv

    - name: Checkout
      uses: actions/checkout@v4

    - run: pip install -e .

    - shell: bash
      run: |
        assert_fail() {
          "$@" && EXIT_CODE="$?" || EXIT_CODE="$?"
          if [ "${EXIT_CODE}" == "0" ]
          then
            exit 1
          fi
        }

        cd examples/hello-lib
        cod build
        cd ../hello-bin
        cod build

        cd ../hc-lib1
        cod build
        cd ../hc-lib2
        cod build
        cd ../hc-bin
        assert_fail cod build
        cod install hc1
        cod build
        assert_fail cod install hc2

        cd ../fc-headers
        cod build
        cd ../fc-lib1
        cod build
        cd ../fc-lib2
        cod build
        cd ../fc-bin
        assert_fail cod build
        cod install fc1
        cod build
        assert_fail cod install fc2
