name: CI

on:
  push:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: pip install -e .

    - run: |
        cd examples/hello-lib
        python -mcod

        cd ../hello-bin
        python -mcod
